version: '3.8'

services:
  app:
    build: .
    container_name: microservice
    ports:
      - '3000:3000'
    environment:
      DB_HOST: sqlserver
      DB_USER: sa
      DB_PASS: YourStrong!Passw0rd
      DB_NAME: master
      FILE_PATH: /app/CLIENTES_IN_0425.dat
    volumes:
      - ../data-generator/challenge/input/CLIENTES_IN_0425.dat:/app/CLIENTES_IN_0425.dat
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-clientes
    environment:
      SA_PASSWORD: 'YourStrong!Passw0rd'
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
